
name: Push to Docker Hub

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Bitwarden Secrets Manager GitHub Action
        uses: bitwarden/sm-action@v1.0.0
        with:
          access_token: ${{ secrets.HW_ACCESS_TOKEN }}
          secrets: |
            69110755-3955-4645-9404-b04501625a05 > DOCKER_USER
            313c412f-968a-443f-b50b-b04a00e490bc > DOCKER_PASSWORD

      - uses: actions/checkout@v3
      - name: docker login
        run: docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
      - name: docker build
        run: |
          docker build -t . --file Dockerfile --tag $DOCKER_USER/hwdocker:latest
      - name: docker push
        run: docker push $DOCKER_USER/hwdocker:latest
